version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Ajustado al puerto del backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db             # Cambiamos localhost por el servicio Docker "db"
      DB_PORT: 3306           # Puerto de MySQL
      DB_USER: neurone        # Usuario de la base de datos
      DB_PASSWORD: neurone123 # Contrase単a del usuario
      DB_NAME: inventarioneurone # Nombre de la base de datos
      NODE_ENV: development   # Entorno de desarrollo
      PORT: 5000             # Puerto en el que corre el backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root123         # Contrase単a del usuario root (puedes cambiarla si deseas)
      MYSQL_DATABASE: inventarioneurone    # Base de datos inicial
      MYSQL_USER: neurone                  # Usuario para la base de datos
      MYSQL_PASSWORD: neurone123           # Contrase単a para el usuario
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123         # Debe coincidir con la contrase単a de root en el servicio db
    restart: always

volumes:
  db_data:
