# Usa una imagen oficial de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./
COPY . .

# Instala las dependencias
RUN npm install

# Expone el puerto que utiliza el backend (4000 en este ejemplo)
EXPOSE 4000

# Comando para iniciar el servidor
CMD ["npm", "start"]
